# build.yml
on:
    pull_request:
      branches:       
      - main 
    push:
      branches:       
      - development        

name: Build and Push to ECR
env: 
    ECR_REPO_NAME: dev01-tmgaming
    REGION: ap-southeast-1 
jobs:
    build-and-push:
      name: Build and deploy
      runs-on: ubuntu-latest
      steps:
  
      - name: Checkout
        uses: actions/checkout@master
  
      # Add steps here like linting, testing, minification, etc.
        
      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # https://github.com/aws-actions/amazon-ecr-login
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
    
    jobs:my-job:
    runs-on: ubuntu-18.04
        
    - name: Get SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      
      - name: Build and tag the image
        env: 
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
            IMAGE_TAG: "latest,test-${{ steps.slug.outputs.sha7 }}"

        run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./app
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
